apiVersion: v1
kind: Pod
metadata:
  name: example
spec:
  containers:
    - image: quay.io/fedora/fedora:35
      name: web
      volumeMounts:
        - mountPath: /test-vol
          name: test-vol
      command:
        - sleep
        - inf
  volumes:
    - name: test-vol
      emptyDir:
        sizeLimit: "2Gi"
